### ISSUE TITLE
Create boilerplate graphics code

### ISSUE THREAD

**Issue by Negabinary** [ThisIsSoNotMe/GaltonBoards#3]
(2d on the plan)

**Comment by AlistairWestmacott** [comment]
Can I get some clarification about this? I understand that I need to get "programmer graphics" working, i.e. enough to do debugging but usability is not a high concern. What exactly is needed? Drawing boards, pins and balls? What would be needed beyond that in task 3d in the plan?

**Comment by Negabinary** [comment]
Yeah I think exactly that, balls (Vector2f pos), pegs (Vector2f pos), boards (Vector2f topleft, Vector2f bottomright), and possibly a line to indicate a connection (Vector2f from, Vector2f to). I think you've got some freedom with regards to how other code interacts with yours. I don't know whether you want to run the positions through a UserView or assume whoever is calling your functions has done it.
